main: moe.rafal.cherry.CherryBukkitPlugin
name: cherry-bukkit-plugin
version: ${project.version}
authors: [shitzuu <hello@rafal.moe>]
api-version: 1.20
depend: ["minePlots", "squaremap", "BH-Endorfy"]